### ISSUE TITLE
Emulator Commands doesnt work again.

### ISSUE THREAD

**Issue by Xanadu16** [jpgohlke/twitch-chat-filter#168]
self-explanatory

Using firefox though.

**Comment by MattiasBuelens** [comment]
Can't reproduce, works fine for me. Tested with version 3.1 in Firefox 36 Beta as Greasemonkey user script and as bookmarklet.

Could you be a bit more specific? Are you running this as a user script or as a bookmarklet? Do the other filters work (cyrillic, dongers,...)? Any errors in the JavaScript console (Ctrl+Shift+K)?

**Comment by Xanadu16** [comment]
Cant re-reproduce either, mark as closed, must have been a fluke. I've been trying to get the bug to appear again and couldn't.
