### ISSUE TITLE
Use HTTPS for Javascript

### ISSUE THREAD

**Issue by RollingStar** [jpgohlke/twitch-chat-filter#171]
https://www.fireeye.com/blog/threat-research/2014/01/js-binding-over-http-vulnerability-and-javascript-sidedoor.html

Anyone with access to one's network (open Wifi, ISP) when they try to load this script can change the HTTP Javascript to some other code. This is a security risk.

**Comment by MattiasBuelens** [comment]
Thanks for the heads-up! I've updated all links to point to the HTTPS version of the script.

Note that many users have downloaded a version of the script locally (as a [Greasemonkey](#installing-the-script-using-greasemonkey-firefox) or [Tampermonkey](#installing-the-script-using-tampermonkey-chrome) script). They should get a notification to update to version 3.3, which uses HTTPS for the download and update URLs. However, until they install the legitimate update, an attacker could still theoretically intercept and modify the automatic update over HTTP.

Also, users who have already [registered the bookmarklet version](http://jpgohlke.github.io/twitch-chat-filter/#using-the-script-as-a-javascript-bookmark) cannot be automatically updated to a HTTPS version. Their bookmarklet will continue serving the HTTP version, unless they manually update to the new URL.
