### ISSUE TITLE
Script currently does not work

### ISSUE THREAD

**Issue by MLSabre** [jpgohlke/twitch-chat-filter#172]
As of current, this script does not function beyond the interface being present (or at the very least, nothing is being filtered since I still see commands coming through). Uncertain if this has to do with Greasemonkey already been updated to 3.6 or BTTV. Also, this has yet to be updated for the current Crystal 251 run. Please update soon.

**Comment by d4mation-** [comment]
It wasn't working for me either, then I realized that [BetterTTV](https://nightdev.com/betterttv/) was breaking it. Once I disabled that everything seemed to work fine.

Try using the Filter in a different browser. When I tried it in Firefox and realized it worked, I figured it must have been another Extension on Chrome breaking it.

**Comment by MattiasBuelens** [comment]
I am running Greasemonkey 3.6 myself, and everything's working fine on my end. My guess would be that BetterTTV is causing problems. We already had a discussion about this in #76, #78 and #105. The conclusion there was that BetterTTV overrides some of Twitch's chat internals in a way that prevents Twitch Chat Filter from adding its own modifications. These issues date back from 2014 however, so maybe I'll take another look to check if BTTV is a bit nicer in newer releases.

Can you confirm that the script is broken **only** when BetterTTV is also active?

-----

Besides, what exactly do you mean with:
>  Also, this has yet to be updated for the current Crystal 251 run.

There's nothing in the chat filter that's specific for a particular TPP run. What feature is not working correctly for you for this run?

**Comment by d4mation-** [comment]
[There are a fair number of new commands in the new run.](https://www.reddit.com/r/twitchplayspokemon/comments/45t454/military_mode/)

That's what I think @MLSabre is talking about. I personally just added `move1`, `move2`, `move3`, and `move4` to my Custom Blacklist. Having something that uses a simple Regex for things like `item<number>` would be much better though since that can range from 1-254 and even be followed by a command to apply to a specific Pokemon.

**Comment by MattiasBuelens** [comment]
@d4mation- Thank you for that link. I haven't been following that closely lately, so I was unaware of the new commands. I'll look into adding them to the commands filter.

**Comment by MLSabre** [comment]
Yes, I can confirm BTTV is what causing problem. Oddly enough, Tampermonkey's version of this script works with BTTV.

As for my mentioning regarding the update, I apologize. I should've clarified about the new commands. as d4mation said, there's a couple new commands that's been made for this run (and for future too perhaps).

**Comment by MattiasBuelens** [comment]
@MLSabre Not a problem, I had to look it up in our issue tracker as well. :stuck_out_tongue: 

I've got a patch ready which adds the military inputs to the commands filter. It looks like BetterTTV did change quite a lot around, so I'm investigating if there's a way to hook into their latest version without breaking everything. If not, I'll just push an update with just the military inputs support in the next couple of days.

**Comment by MattiasBuelens** [comment]
Military input filtering landed in version 3.4, update your user script or re-load your bookmarklet to get it. :smiley: 

BetterTTV is still a mess. To make a long story short, it hooks into Twitch's UI code (similar to TCF), throws out all the UI rendering code and replaces it with its own UI. In order for TCF to support this, we would have to write code to hook into BetterTTV *specifically*. Keeping TCF working whenever Twitch updates their own UI code is already a pain in the bum, and I don't really want to maintain code depending on the internal workings of a rapidly changing extension like BetterTTV.

If someone wants to spend a couple of evenings to implement BetterTTV support, feel free to submit a PR. But be warned that I'd probably ask you to help maintain the code as well whenever BetterTTV changes something on their side. :stuck_out_tongue:

**Comment by hugomg** [comment]
Given how often people report this BetterTTV issue I wonder if there is a way we can at least give  a good error message. Something like "BetterTTV is incompatible with Twitch-chat-filter. Please disable BetterTTV to use twitch-chat-filter".

Is there an easy way to detect if someone is using BetterTTV?
