### ISSUE TITLE
No live stream is playing, chat is covering the video

### ISSUE THREAD

**Issue by LittleEndu** [jpgohlke/twitch-chat-filter#176]
For live channels, there is no video. And the place that is supposed to have the video is covered by chat.
Running on vanilla with no plugins using Chrome and TamperMonkey.

**Comment by MattiasBuelens** [comment]
Confirmed. Chat pops up in the wrong place, video won't start playing and we're spamming the browser console with JavaScript errors. In other words, looks like Twitch changed their UI code again. :stuck_out_tongue:
